# 코퍼스 결손 지도 — 무엇을 넣어야 하는가 (2026-08-26)

수집은 하지 않았다. **무엇이 필요한지만 특정한다.** 크롤링·인제스트·bake 재실행
없음. 이 문서에 코퍼스 본문은 인용하지 않았다 — 식별자와 개수만 쓴다.

근거는 사람이 승인한 gold 배치1 40건(`ad403b3`)과 bake 지문
`sha256:db11af7e…`가 일치하는 코퍼스(문서 277청크 + 영상 35청크)다.

---

## [1] 결손 지도 — `curriculum_axis` × `query_type`

실질 32건 = answerable 9 / partial 7 / missing 16. `refuse_boundary` 8건은
코퍼스에 없는 것이 정답이므로 제외했다.

셀 표기는 **`missing / partial / (answerable)`**. `·`는 그 조합의 질의가 아예
없다는 뜻이다 — **측정된 적이 없는 칸**이지 커버된 칸이 아니다.

| 축 | definition | procedure | situation | differential | 행 합계 |
|---|---|---|---|---|---|
| 배변 | · | 0 / 1 / (1) | 0 / 1 / (0) | · | 0 / 2 / (1) |
| 산책 | 1 / 0 / (0) | 1 / 0 / (0) | 0 / 1 / (0) | 1 / 0 / (0) | **3 / 1 / (0)** |
| 물기 버릇 예방 | 1 / 0 / (0) | 0 / 1 / (0) | 1 / 0 / (0) | · | **2 / 1 / (0)** |
| 하우스 | 0 / 0 / (1) | 0 / 0 / (1) | · | · | 0 / 0 / (2) |
| 스킨십 | · | 0 / 1 / (0) | 1 / 1 / (0) | · | **1 / 2 / (0)** |
| 이름 | · | 1 / 0 / (0) | 1 / 0 / (0) | · | **2 / 0 / (0)** |
| 아이컨택 | 1 / 0 / (0) | 1 / 0 / (0) | 1 / 0 / (0) | · | **3 / 0 / (0)** |
| 명령어 | · | 1 / 0 / (1) | · | · | 1 / 0 / (1) |
| (축 미지정) | 1 / 0 / (2) | · | 1 / 0 / (2) | 2 / 1 / (1) | 4 / 1 / (5) |
| **열 합계** | 4 / 0 / (3) | 4 / 3 / (3) | 5 / 3 / (2) | 3 / 1 / (1) | **16 / 7 / (9)** |

### 이 표에서 읽히는 것

- **answerable이 0인 축이 5개다** — 산책, 물기 버릇 예방, 스킨십, 이름, 아이컨택.
  이 축들은 코퍼스가 한 번도 정답을 낸 적이 없다.
- **아이컨택·이름은 partial조차 0이다.** 얕은 근거도 없다.
- **`definition` 열이 특히 비었다.** 배변·스킨십·이름·명령어 4개 축에 정의형
  질의 자체가 없어 측정된 적이 없고, 측정된 4건은 전부 missing이다.
- 산책은 축 전체로 보면 질의가 4건으로 가장 많은데 answerable이 0이다.
- `(축 미지정)` 18건 중 여기 나오는 것은 10건이다(나머지 8건이
  `refuse_boundary`). 실제 견주 질문체에서 뽑은 질의라 축이 없다.

---

## [2] 결손 원인 분류

`(a)` 주제 자체가 없음 · `(b)` 주제는 있으나 그 각도가 없음 ·
`(c)` 있는데 청킹·파싱 때문에 검색이 안 됨.

### 먼저 — 점수는 판정 근거가 되지 못한다

최근접 후보의 코사인 점수를 coverage별로 모았다.

| coverage | n | min | 중앙 | max |
|---|---:|---:|---:|---:|
| answerable | 9 | 0.779 | 0.865 | 0.888 |
| partial | 7 | 0.835 | 0.862 | 0.867 |
| **missing** | 16 | 0.774 | 0.833 | **0.870** |
| refuse_boundary | 8 | 0.818 | 0.843 | 0.870 |

**구간이 겹친다.** missing의 최대(0.870)가 answerable의 최소(0.779)보다 높고,
거절해야 할 질의도 0.870까지 나온다. 그래서 아래 분류는 점수가 아니라 **용어의
코퍼스 전수 출현**과 사람의 `label_reason`에 근거한다.

### 용어 전수 스캔 (문서 277 + 영상 35 = 312청크)

| 용어 | 출현 청크 |
|---|---:|
| `아이컨택` / `아이 컨택` / `눈맞` / `눈을 맞` / `시선` | **0** |
| `자원 보호` / `자원보호` | **0** |
| `리버스` / `역재채기` | **0** |
| `리콜` | **0** |
| `꼬리를 흔` | **0** |
| `마킹` | 1 (분리불안 문서 안, 주제 무관) |
| `이리와` | 1 (영상 1청크) |
| `한숨` | 1 |

### 분류표 — missing 16건

| qid | 축 / 유형 | 분류 | 최근접 청크 (점수) | 근거 |
|---|---|:--:|---|---|
| g005 | 아이컨택 / def | **(a)** | `wayopet-night-lunging-answer` (0.823) | 관련 용어 0청크 |
| g016 | 아이컨택 / proc | **(a)** | `KhNJl8kj7ks` (0.835) | 관련 용어 0청크 |
| g024 | 아이컨택 / situ | **(a)** | `wayopet-night-lunging-answer` (0.870) | 관련 용어 0청크 |
| g007 | 물기 / def | **(a)** | `wayopet-noise-barking-answer` (0.774) | `자원 보호` 0청크 |
| g003 | (없음) / def | **(a)** | `wayopet-fear-barking-answer` (0.805) | `리버스`·`역재채기` 0청크 |
| g028 | (없음) / diff | **(a)** | `wayopet-walk-lunging-answer` (0.828) | `꼬리를 흔` 0청크 |
| g029 | (없음) / diff | **(a)** | `berrardog-separation-anxiety-…` (0.852) | `한숨` 1청크, 주제 무관 |
| g014 | 명령어 / proc | **(a)** | `KhNJl8kj7ks` (0.821) | `이리와` 1청크(영상), `리콜` 0 |
| g002 | 산책 / def | **(a)** | `9FWfbXwXbP0` (0.817) | `마킹` 1청크, 주제 무관 |
| g023 | (없음) / situ | **(a)** | `wayopet-night-lunging-question` (0.863) | 야간 흥분 대처 서술 없음 |
| g022 | 스킨십 / situ | **(b)** | `Ry3NnrbVjAM` (0.844) | 스킨십 축 5문서 40청크 있으나 양치 **거부 대처** 각도 없음 |
| g017 | 산책 / proc | **(b)** | `wayopet-walk-lunging-question` (0.830) | 산책 축 16문서 107청크 있으나 발 닦기 절차 없음 |
| g030 | 산책 / diff | **(b)** | `wayopet-walk-lunging-question` (0.852) | 산책 축은 두껍고 이 논점만 없음 |
| g009 | 이름 / proc | **(a′)** | `KhNJl8kj7ks` (0.850) | 주제 매칭이 `OWNER_QUESTION`뿐 — 아래 |
| g018 | 이름 / situ | **(a′)** | `wayopet-walk-lunging-question` (0.831) | 최근접이 `citation_allowed=False` |
| g021 | 물기 / situ | **(a′)** | `Ry3NnrbVjAM` (0.856) | 후보 20개 중 8개가 `OWNER_QUESTION` |

집계: **(a) 10건 · (a′) 3건 · (b) 3건 · (c) 0건.**

### (c)는 0건이다 — 수집 문제이지 파이프라인 문제가 아니다

16건 어디에도 "청크에 답이 있는데 검색이 못 찾은" 사례가 없다. 용어 전수
스캔에서 대상 개념이 아예 나오지 않는다. **파이프라인을 고쳐서 해소되는 결손은
없다.**

### (a′) — 새로 만든 칸이다

`(a)`의 하위 갈래로 표시했다. **주제가 코퍼스에 나타나기는 하는데 견주 질문
쪽에만 나온다.** wayopet Q&A 문서는 질문/답변이 분리돼 있고 질문 쪽은
`segment_role=OWNER_QUESTION` · `citation_allowed=False`다. 검색은 그것을
찾아내지만 gold로 쓸 수 없다.

이것은 파싱 버그가 아니라 권위 계약(`docs/design_qa_authority_retrieval.md`)이
의도한 동작이므로 `(c)`가 아니다. **고치는 방법도 파이프라인이 아니라 수집이다**
— 그 주제를 **답변 쪽에서** 다루는 문서가 필요하다.

g018·g021은 최근접 후보 자체가 `citation_allowed=False`다. 즉 지금 검색기는
"관련 있는 것"을 찾고 있는데 그게 전부 인용 불가다.

---

## [3] 현재 코퍼스 프로파일

**축 배정은 키워드 휴리스틱이다.** 문서·영상 청크에 축 필드가 없어 축별 대표
용어의 출현으로 근사했고, 한 문서가 여러 축에 중복 배정된다. 절대값이 아니라
**어디가 0인가**를 보는 용도다.

| 축 | 문서 | 문서 청크 | 영상 청크 | gold 결손 (missing/partial) |
|---|---:|---:|---:|---|
| 산책 | 16 | 107 | 6 | 3 / 1 |
| 명령어 | 14 | 84 | 3 | 1 / 0 |
| 하우스 | 10 | 67 | 1 | 0 / 0 |
| 배변 | 6 | 51 | 2 | 0 / 2 |
| 스킨십 | 5 | 40 | 6 | 1 / 2 |
| 물기 버릇 예방 | 3 | 21 | 2 | 2 / 1 |
| **이름** | **1** | **5** | **1** | **2 / 0** |
| **아이컨택** | **0** | **0** | **0** | **3 / 0** |
| (미배정) | 4 | — | 10 | — |

문서 29개 / 277청크, 영상 3개 / eligible 26청크.

### 나란히 놓으면 보이는 것

- **아이컨택은 문서·영상 모두 0이다.** 결손 지도의 3 missing과 정확히 맞는다.
  이 축은 "부족"이 아니라 "없음"이다.
- **이름은 1문서 5청크뿐**이고, 그마저 gold에서는 `OWNER_QUESTION` 매칭으로만
  잡혔다(g009·g018). 실질적으로 답변 쪽 자료가 0이다.
- **산책은 문서가 가장 많은데(16문서 107청크) answerable이 0이다.** 양이
  아니라 각도의 문제다 — [2]에서 산책 결손 3건 중 2건이 `(b)`로 분류된 것과
  같은 이야기다. **산책 축에 문서를 더 넣는 것은 답이 아니다.**
- 하우스는 10문서 67청크에 결손 0이다. 여기가 "충분히 채워진 축"의 기준선이 된다.

---

## [4] 수집 대상 제안

출처는 특정하지 않는다. **필요한 주제와 서술 각도만** 적는다. 각 항목에 그것이
해소하는 질의 id를 붙였고, **id가 붙지 않는 제안은 넣지 않았다.**

| # | 필요한 것 | 각도 | 건수 | 해소 질의 |
|---|---|---|---:|---|
| 1 | **아이컨택 훈련** | 정의 · 교육 절차 · 간식에 시선이 뺏길 때의 대처 | 3 | g005, g016, g024 |
| 2 | **호명 반응(이름) 훈련** — 답변 쪽 서술 | 절차 · 이름을 부르면 도망가는 상황 | 2 | g009, g018 |
| 3 | **자원 보호(resource guarding)** | 개념 정의 · 밥그릇 접근 시 으르렁 대처 | 2 | g007, g021 |
| 4 | **산책 세부 각도** (새 산책 일반론 아님) | 마킹의 정의 · 산책 후 발 닦기 절차 · 냄새 맡게 두기의 가부 | 3 | g002, g017, g030 |
| 5 | **리콜(이리와) 완성 절차** | 오다가 새는 단계의 교정 절차 | 1 | g014 |
| 6 | **양치 거부 대처** | 스킨십 축에 이미 있는 자료의 빈 각도 | 1 | g022 |
| 7 | **행동 신호 감별** | 꼬리 흔들기의 의미 · 한숨의 의미 | 2 | g028, g029 |
| 8 | **야간 과흥분 대처** | 상황 대처 절차 | 1 | g023 |
| 9 | **리버스 스니징** | 정의 및 기침과의 감별 | 1 | g003 |

합계 **16건, missing 16건 전부에 대응**한다.

### 우선순위와 주의

- **1·2·3번이 먼저다.** 축이 통째로 비어 있고(`아이컨택` 0청크, `이름` 답변 쪽
  0), `(a)`/`(a′)`라 문서를 넣으면 그대로 해소된다.
- **4·6번은 양이 아니라 각도를 사야 한다.** 해당 축은 이미 두껍다(산책 16문서,
  스킨십 5문서). 같은 성격의 일반론을 더 넣으면 경쟁자만 늘고 결손은 그대로다.
- **9번(리버스 스니징)은 의료 경계와 겹친다.** `refuse_boundary` 8건이 수의
  진단을 거절하도록 돼 있는데, 리버스 스니징은 증상 감별이라 가드레일이
  거절해야 할 대상인지 먼저 판정이 필요하다. **판정 전에는 수집하지 말 것.**
- 7번도 `differential` 유형이라 "단정하지 않는 서술"이 필요하다. 근거 없이
  단정하는 블로그 글을 넣으면 답변 품질이 아니라 신뢰도가 깎인다.

---

## [5] 확장 후 재측정 계획 (설계만)

### 5-a 앵커 — 평가는 안 깨지고, **import이 막힌다**

현재 앵커 7개는 전부 1청크 / 1문서에 매칭된다.

| anchor | 길이 | doc_id |
|---|---:|---|
| g013-a1 | **25** | `easiestip-kennel-training` |
| g004-a2 | **26** | `wayopet-fear-barking-answer` |
| g008-a1 | **27** | `fitpet-potty-training` |
| g004-a1 | 32 | `wayopet-walk-training-answer` |
| g006-a1 | 38 | `easiestip-kennel-training` |
| g031-a1 | 57 | `easiestip-isolation-vs-separation-anxiety` |
| g012-a1 | 58 | `easiestip-wait-training` |

**두 경로가 비대칭이다. 이것이 이 절의 핵심이다.**

- **평가(`gold_relevant_chunks`)는 안전하다.** 앵커를 먼저 `doc_id`로 좁힌 뒤
  (`in_doc = [c for c in document_chunks if c["doc_id"] == anchor["doc_id"]]`)
  그 안에서 인용문을 찾는다. **다른 문서에 같은 문장이 생겨도 gold는 오염되지
  않는다.**
- **import(`revalidate_anchor`)는 막힌다.** 이쪽은 코퍼스 전체에서 인용문을
  찾고 매칭 문서가 2개 이상이면 거부한다. 확장 후 gold를 다시 기록하려 하면
  **평가에는 아무 문제가 없는데 import이 거부하는** 상황이 생긴다.

위험이 높은 것은 짧은 3개(25·26·27자)이고, 그중 **`easiestip-kennel-training`에
두 개(g006·g013)가 몰려 있다.** 제안 4·6번처럼 기존 축을 보강할 때 켄넬·배변
계열 문서가 들어오면 여기가 먼저 걸린다.

**설계 판단이 필요한 지점**: `revalidate_anchor`를 평가와 같은 규약(`doc_id`
스코프 우선)으로 맞출 것인가, 아니면 지금의 엄격함을 유지하고 걸릴 때마다
인용문을 늘릴 것인가. 구현하지 않았다.

### 5-b 영상 span — 영향 없음, 다만 지금은 공허하다

문서를 추가해도 영상 청크의 `chunk_id`는 바뀌지 않는다(영상 청킹 입력이 다르다).
`gold_relevant_chunks`도 span을 `by_video = [c for c in video_chunks if
c["video_id"] == query["video_id"]]`로 먼저 좁힌 뒤 시간 겹침만 본다. 문서
확장이 닿는 경로가 없다. **확인 완료.**

다만 **현재 gold 40건 중 span을 쓰는 행은 0개다.** 영상 gold 4건(g010·g011·
g020·g027)은 아직 기록되지 않았다(B-3 설계 대기). 그러므로 "영상 span은 안전"은
지금으로선 지킬 것이 없다는 뜻이기도 하다.

### 5-c `resolved_at` 재판정 — 여기가 진짜 제약이다

`resolved_at`은 사람이 자유롭게 적는 값이 아니라 **bake가 만든 후보 풀에서
어느 단계에 근거가 나왔는가**를 가리킨다. 그래서:

1. **코퍼스가 바뀌면 `resolved_at` 40건 전부가 무효가 된다.** 후보 풀이 달라지고
   `vector_top5`/`vector_top20`/`lexical`의 경계가 이동한다. 일부가 아니라 전부다.
2. **재판정하려면 bake를 다시 구워야 한다.** 그 외의 방법이 없다.
3. **bake를 다시 구우면 작업대 지문이 바뀐다.** 키는
   `dogtrain-gold-batch1-<wf>`이고 `wf`는 `bake.corpus.fingerprint`와 후보
   `chunk_id` 목록을 포함해 계산된다(`gold_workbench.html:174`). 코퍼스가 바뀌면
   `wf`가 바뀌고 **진행 중이던 localStorage 라벨링을 못 읽는다.**

**따라서 순서가 강제된다:**

```
지금 → 배치1 라벨링·export 완결, gold 파일 커밋 (완료: ad403b3)
     → B 구현으로 채점 불가 10건 복구        ← 아직
     → 확장 전 기준선 재측정 (채점 16건)      ← 아직
────────────────── 여기까지 끝난 뒤에만 ──────────────────
     → 코퍼스 확장 (수집·인제스트)
     → bake 재실행 (배치2)
     → resolved_at 재판정
```

**확장을 먼저 하면 배치1 라벨링을 다시 하게 된다.** 지금 gold 파일이 커밋돼
있으므로 라벨 자체는 잃지 않지만, `resolved_at`은 새 bake 없이는 복원되지 않는다.

### 5-d `coverage`가 `missing` → `answerable`로 바뀌는 것은 사람이 한다

`coverage`는 bake가 계산하지 않는다. 사람의 판정이다. 확장 후 절차는:

1. 새 코퍼스로 bake (배치2) — 40건 중 **missing 16건만** 다시 후보를 뽑아도 된다.
   answerable 9건·partial 7건은 근거가 이미 있고, 새 문서가 더 나은 근거를 줄
   수는 있으나 그건 별개 판단이다.
2. 작업대에서 그 16건을 사람이 다시 본다. 새 문서가 답을 주면
   `missing → answerable/partial`로 바꾸고 앵커를 잡는다.
3. `import_gold_labels.py`로 기록. `corpus_fingerprint`가 행마다 새 값으로 바뀐다.
4. **바뀌지 않은 행의 `corpus_fingerprint`도 함께 갱신할지** 정해야 한다. 섞이면
   한 파일 안에 두 시점의 지문이 공존한다. 지금 스키마는 이 경우를 다루지 않는다.

4번은 미해결로 남긴다. 설계만 하라 했으므로 구현하지 않았다.

---

## 하지 않은 것

수집·크롤링·인제스트 없음. bake 재실행 없음. 푸시 없음. 코드 변경 없음.
이 문서에 코퍼스 본문 인용 없음.
